import { ClerkProvider, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Battle Leetcode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      frontendApi={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className={inter.className + " font-sans bg-gray-50"}>
          <header className="bg-transparent shadow-lg">
            <nav className="flex items-center justify-between px-6 py-4">
              <Link href="/" passHref>
                <p className="text-2xl font-bold text-gray-900">Battle Leetcode</p>
              </Link>
              <div className="flex items-center space-x-4">
                <SignedOut>
                  <Link href="/sign-in" passHref>
                    <p className="text-gray-900 hover:underline">Sign-In</p>
                  </Link>
                  <Link href="/sign-up" passHref>
                    <p className="text-gray-900 hover:underline">Sign-Up</p>
                  </Link>
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </nav>
          </header>

          {/* Content */}
          <main className="min-h-screen pt-4">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
